import Head from 'next/head'
import {BsFillMoonStarsFill} from 'react-icons/bs'
import {AiFillTwitterCircle, AiFillLinkedin, AiFillYoutube} from 'react-icons/ai'
import Image from 'next/image'
import deved from '../public/dev-ed-wave.png'
import anton from '../public/Antony.png'


const cover = { objectFit: "cover" }

export default function Home() {
  return (
    <div>
      <Head>
        <title>Antoni Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className='bg-white px-10'>
        <section className='min-h-screen'>
          <nav className='py-10 mb-12 flex justify-between'>
            <h1 className='text-xl text-gray-600'>developedbyantony</h1>
            <ul className='flex items-center'>
              <li>
                <BsFillMoonStarsFill className='cursor-pointer text-2xl'/>
              </li>
              <li><a className='bg-gradient-to-r from-cyan-500 to-teal-500 text-white px-4 py-2 rounded-md ml-8' href="#">Resume</a></li>
            </ul>
          </nav>
          <div className='text-center p-10'>
            <h2 className='text-5xl py-2 text-teal-600 font-medium'>Antony Syah</h2>
            <h3 className='text-2xl py-2'>Developer and Designer</h3>
            <p className='text-md py-5 leading-8 text-gray-600'>Freelancer providing service for programming and desain content needs. Join me down below and let's get cracking!</p>
          </div>
          <div className='text-5xl flex justify-center gap-16 py-3 text-gray-600'>
            <AiFillTwitterCircle />
            <AiFillLinkedin />
            <AiFillYoutube />
          </div>
          <div className='relative mx-auto bg-gradient-to-b from-teal-500 rounded-full w-80 h-80 mt-20 overflow-hidden'>
            <Image src={anton} fill style={cover} />
          </div>
        </section>

        {/* create service */}
        <section>
          <div>
            <h3 className='text-3xl py-1'>Service I offer</h3>
            <p className='text-md py-2 leading-8 text-gray-800'>Since the begining of my journey as a free developer, I've done remote work for<span className='text-teal-500'> agency</span>consulted for <span className='text-teal-500'> startups</span>
            </p>
          </div>
        </section>
      </main>

     
    </div>
  )
}
 